import type { AgentEvent, DaemonEventMetadata, Session } from '@kode/protocol'

export type ToolPermissionDecision = 'allow_once' | 'allow_always' | 'deny'

export type ToolPermissionInputUpdate = Record<string, unknown>

/**
 * Request-scoped options shared by direct and daemon-backed clients.
 *
 * `clientMessageUuid` is generated by `HttpClient` when omitted. Supplying a
 * stable value lets a caller retry an optimistic user message without creating
 * a second logical prompt.
 */
export type SendMessageOptions = {
  clientMessageUuid?: string
}

/**
 * The client-facing form of a daemon event.
 *
 * Raw `AgentEvent` remains valid for direct/legacy transports. Daemon-backed
 * clients attach correlation metadata when the server opts into its envelope.
 */
export type CorrelatedAgentEvent = AgentEvent & Partial<DaemonEventMetadata>

export type RuntimeStatus = {
  ok: boolean
  transport: 'direct' | 'daemon'
  pid: number | null
  version: string | null
  activeSessions: number | null
}

/**
 * KodeClient is the UI-facing SDK for driving a Kode session.
 *
 * Implementations:
 * - DirectClient: in-process (CLI/VSCode/Desktop main process)
 * - HttpClient: remote (Web, or any client that talks to `apps/server`)
 */
export interface KodeClient {
  /**
   * Send a user message and stream back events until the request completes.
   */
  sendMessage(
    message: string,
    options?: SendMessageOptions,
  ): AsyncGenerator<CorrelatedAgentEvent>

  /**
   * Cancel the active request, if any.
   */
  cancelRequest(): void

  /**
   * Approve an in-flight tool permission request.
   *
   * `toolUseId` maps to the request identifier emitted by the server. In
   * daemon/WS mode this is aligned to the tool_use id when available.
   */
  approveToolUse(
    toolUseId: string,
    options?: {
      decision?: Exclude<ToolPermissionDecision, 'deny'>
      updatedInput?: ToolPermissionInputUpdate | null
    },
  ): Promise<void>

  /**
   * Deny an in-flight tool permission request.
   */
  denyToolUse(
    toolUseId: string,
    reason?: string,
    options?: { updatedInput?: ToolPermissionInputUpdate | null },
  ): Promise<void>

  /**
   * List known sessions for the current workspace.
   */
  listSessions(): Promise<Session[]>

  /**
   * Read backend runtime availability without attaching a live session.
   */
  getRuntimeStatus(): Promise<RuntimeStatus>

  /**
   * Load a session. Implementations may return metadata-only if full message
   * history is not available via a single call.
   */
  loadSession(sessionId: string): Promise<Session>

  /**
   * Delete a session and its persisted history (if supported).
   */
  deleteSession(sessionId: string): Promise<void>

  /**
   * True when the underlying transport is connected.
   */
  isConnected(): boolean

  /**
   * Disconnect the underlying transport.
   */
  disconnect(): void
}

/**
 * Optional session-aware capabilities exposed by remote clients.
 *
 * This is a separate interface so existing in-process `KodeClient`
 * implementations, including `DirectClient`, remain source compatible.
 */
export interface SessionAwareKodeClient extends KodeClient {
  /** Attach to an existing session and wait for init plus history replay. */
  attachSession(sessionId: string): Promise<void>

  /** Start a new session and return the id announced by its init event. */
  startSession(): Promise<string>

  /** Subscribe to all validated agent events for the attached session. */
  subscribeEvents(listener: (event: CorrelatedAgentEvent) => void): () => void

  /** Return the session id most recently confirmed by the server. */
  getAttachedSessionId(): string | null
}
